IF COL_LENGTH('CLIENTES', 'CPF') IS NULL
BEGIN
    ALTER TABLE CLIENTES
    ADD CPF VARCHAR(11) NULL
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_CLIENTES_CPF'
      AND object_id = OBJECT_ID('CLIENTES')
)
BEGIN
    CREATE UNIQUE INDEX UX_CLIENTES_CPF
    ON CLIENTES (CPF)
    WHERE CPF IS NOT NULL
END
GO
