CREATE OR ALTER PROC FI_SP_AltBeneficiario
    @ID BIGINT,
    @CPF VARCHAR(11),
    @NOME VARCHAR(50)
AS
BEGIN
    UPDATE BENEFICIARIOS
    SET CPF = @CPF,
        NOME = @NOME
    WHERE ID = @ID
END
