CREATE OR ALTER PROC FI_SP_VerificaBeneficiario
    @CPF VARCHAR(11),
    @IDCLIENTE BIGINT,
    @ID BIGINT = 0
AS
BEGIN
    SELECT ID
    FROM BENEFICIARIOS WITH(NOLOCK)
    WHERE CPF = @CPF
      AND IDCLIENTE = @IDCLIENTE
      AND (ISNULL(@ID, 0) = 0 OR ID <> @ID)
END
