CREATE OR ALTER PROC FI_SP_ConsBeneficiarios
    @IDCLIENTE BIGINT
AS
BEGIN
    SELECT ID, CPF, NOME, IDCLIENTE
    FROM BENEFICIARIOS WITH(NOLOCK)
    WHERE IDCLIENTE = @IDCLIENTE
    ORDER BY NOME ASC
END
