CREATE OR ALTER PROC FI_SP_DelCliente
	@ID BIGINT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN

		DELETE FROM BENEFICIARIOS WHERE IDCLIENTE = @ID
		DELETE FROM CLIENTES WHERE ID = @ID

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRAN

		THROW
	END CATCH
END